# Generated by Django 4.0.2 on 2022-03-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
    ]
